### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by kelshiekh** [hfaridgit/Cheque-Management#3]
Hi I really need this module but every time I try to install I get an error no module found cheque_management and after that get  server error

**Comment by hfaridgit** [comment]
If you are in newer versions 10 and up you should change the setup.py file.

**Comment by kelshiekh** [comment]
I am in version 13
what should I change in setup.py if you pleas

**Comment by kelshiekh** [comment]
I am very sorry for the inconvenience but I really need this module argent

**Comment by hfaridgit** [comment]
Updated
Please try again now

**Comment by kelshiekh** [comment]
Many thanks I tried again and it is installed probably, I appreciate your effort with me
